### ISSUE TITLE
Error after disabling then enabling device

### ISSUE THREAD

**Issue by WebAiz** [kybarg/ebds#3]
Hello, sometimes i get ack error when I'm disabling and then enabling device. Is there a way to handle this, as I need to continue the flow of the app even if device sends me error. I need to resolve this error and continue using the device. Thanks

**Comment by kybarg** [comment]
Currently libarary doesn't automatically handle ACK/NAK change in case of an error. (semm need to implement it😊, but later)

### Solution 1
You can set **ackNumber** manually, but keep in mind that when running `command` method it chnages ACK to opposite due to implementation https://github.com/kybarg/ebds/blob/main/lib/index.js#L138
```javascript
 cosnt ebds = new EBDS();

// setting
ebds.ackNumber = 0;
// will send command ackNumber === 1 and vice versa
ebds.command('ENABLE'); 
```

![image](https://user-images.githubusercontent.com/4588778/202650114-a3e8c7e8-58d3-4818-9f3a-c8a2defe4ad8.png)

### Solution 2
Some models require some tweaking, for exampel _escrow mode_ disabled or _extended note reporting_ disabled in order to work. 
Information on that can be found here
http://se2000.ru/download_programms/protokoli/RETAIL%20EBDS%20PROTOCOL%20SPECIFICATION%20with%20MPOST%20G2.pdf

### Solution 3
You might not need **enable/disable** method at all.
I don't have any hardware on my hands, had to develop it by specification and tested remotely, so not sure about **enable/disable** functions 100%.
From what I know, acceptor enables as soon as you start polling it and turns off after _3s_ you stop

**Comment by WebAiz** [comment]
Hello, also I want to implement close method, which fully defaults all configs of EBDS class. So after reopening it I could use it from fresh. Right now after calling close method of serialPort instance, then calling open method of EBDS instance, I'm getting an error. Do you have any idea what I'm doing wrong? Thanks

**Comment by kybarg** [comment]
@WebAiz need code example, but answer to your problem might be here https://github.com/kybarg/ebds/blob/main/lib/index.js#L21-L52

**Comment by WebAiz** [comment]
I figured out that sometimes after DISABLE command, the polling wont stop, and device will be in idling state and subsequent commands like ENABLE will result an ACK/NAK error

**Comment by kybarg** [comment]
@WebAiz "DISABLE"  command is a gimmick... It says device to close all channels for accepting bills first before stopping polling.
https://github.com/kybarg/ebds/blob/main/lib/index.js#L45
I think you device/currency has different value of denominations. To disable device you can simly run `ebds.poll(false);`
let me know if it works.

**Comment by kybarg** [comment]
@WebAiz also originally was developed and tested on **SCN83**, so it might need some tweaking for other devices
